### ISSUE TITLE
(BUG) User notifications when request is complete not working

### ISSUE THREAD

**Issue by ksbansal** [tidusjar/PlexRequests.Net#541]
I can't get the "Send me a notification when items I have requested have been added" feature to work.
I have enabled:

Enabled
Enabled user email notifications
Enabled SMTP Authentication

under the email settings and using:

SMTP Host name or IP
smtp.gmail.com

SMTP Port
465

Email Sender
@gmail.com

Email Recipient
@gmail.com

Username
@gmail.com

Password
•••••••••••••••

The test works fine.

Please fix this issue ASAP please, or tell me what I'm doing wrong. PlexRequests.NET is awesome but this is one of the features that got me using it. Sorry if I made any mistakes I'm new here :+1: 

#### Plex Requests.Net Version:
1.9.1

#### Operating System:
windows server 2012 r2

#### Mono Version:
not sure

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Not sure what part of the logs I should be looking at
```

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
> Send me a notification when items I have requested have been added
This only applies to the users (not an admin or Plex Owner) that are requesting.

**Comment by tidusjar** [comment]
Do you also have 2 factor auth on your GMail account?

**Comment by tidusjar** [comment]
I just got this when using GMail:

![image](https://cloud.githubusercontent.com/assets/6642220/18616983/6456edb0-7dbe-11e6-806a-5fc7b3e7c35f.png)

**Comment by ksbansal** [comment]
I don't have 2 factor authentication enabled. Regarding the email I just enabled "allow less secure apps" which worked for the test email, and also works for email notifications on plexpy. I also tested the notification sytem for requests using my brothers account whos part of my userbase. Requested a number of movies using his account with admin logged out and he didn't get any email notifications.

**Comment by tidusjar** [comment]
OK! I'll keep looking, can you just make sure this is not a problem with the latest release (1.9.2) as I have fixed a few issues around notifications

**Comment by ksbansal** [comment]
Sorry my friend. Your latest release doesn't seem to fix the issue.

**Comment by tidusjar** [comment]
Did you close this by accident then?

**Comment by ksbansal** [comment]
yes sorry about that. Can you reopen?

**Comment by ksbansal** [comment]
yes sorry ill reopen.

**Comment by tidusjar** [comment]
Hello,

I have just tested all of this and it seems to work fine.

Can you please confirm that the email addresses are correct here:

https://plex.tv/pms/friends/all

**Comment by ksbansal** [comment]
yes the emails are correct

**Comment by tidusjar** [comment]
Anything in spam?

You should be able to see the item in your sent folder in gmail.

Also what smtp server and port are you using?

**Comment by ksbansal** [comment]
ok so the problem was with the plex user email i tested for some reason it wan't receiving any emails. i just tested a different account but it goes to junk. is their any way to prevent this?

so it works but to juck :(
